# Site settings
title: Leo's Portfolio
description: Leo's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leodong.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# run below for prod
# jekyll build -d '/var/www/html/'
# jekyll serve --source src --destination dist

# User settings
username: Leo Dong
user_description: Data Scientist at the Commonwealth Bank of Australia. Keen photographer as well.
user_title: Data Scientist
email: leozhdong@gmail.com
github_username: leoodong
linkedin_username: dongleo
smugmug_url: "https://photo.leodong.me"
medium_username: leozhdong


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
